# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlapSkills < Formula
  desc "CLI to manage your opencode skills from any git repo"
  homepage "https://github.com/vekzz-dev/slap-skills"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Darwin_x86_64.tar.gz"
      sha256 "6bd3284a509afe9b76931c93a9dd1623e12e9ae107a09cdb80eed154c988ecfe"

      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Darwin_aarch64.tar.gz"
      sha256 "fa29e9f3e1782da369b9560f356e6982ce1c0680ce750e79688440700703ed1b"

      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Linux_x86_64.tar.gz"
      sha256 "28ff8d2c9434b9afaaebe96a637433f65a8d5a6761dbb7e7f8bb2641372d187c"
      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Linux_aarch64.tar.gz"
      sha256 "e516f5a8a5e220fa58e3234f8ad182f2847ca66a35bbeae3e0fa79d318e732e8"
      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  test do
    system "#{bin}/slap", "--help"
  end
end
