# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlapSkills < Formula
  desc "CLI to manage your opencode skills from any git repo"
  homepage "https://github.com/vekzz-dev/slap-skills"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Darwin_x86_64.tar.gz"
      sha256 "eac27ddb0f06ed1d569838b4daddd94828c2d76742ead4ae1babff97cf8f3b67"

      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Darwin_aarch64.tar.gz"
      sha256 "0153f11e174d0b83fdb637e4da1d67a5f6e166892e52e06ef277304581d43b6b"

      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Linux_x86_64.tar.gz"
      sha256 "bee91ee078c67bc41bf305ab5a50f5f12473cc70338cece4307b6a24f3b8f4fe"
      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Linux_aarch64.tar.gz"
      sha256 "379c715ba85575b83beca643971f9da6692fb91dbbc089ac0b5c8ae715b2ad62"
      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  test do
    system "#{bin}/slap", "--help"
  end
end
