# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlapSkills < Formula
  desc "CLI to manage your opencode skills from any git repo"
  homepage "https://github.com/vekzz-dev/slap-skills"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.2.1/slap-skills_Darwin_x86_64.tar.gz"
      sha256 "9891f0203bbebcfc845d78931253271d289e1fd8d1af947790263ee8316fcce3"

      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.2.1/slap-skills_Darwin_aarch64.tar.gz"
      sha256 "0bdaecbbec081a22d92d46ba6be902a1bb8a24441558c71074af738c5d9bb7de"

      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.2.1/slap-skills_Linux_x86_64.tar.gz"
      sha256 "111ec32b627782bf1b82e4fedf99fb145ca31884165ee57c21b35ae5adcb274e"
      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.2.1/slap-skills_Linux_aarch64.tar.gz"
      sha256 "ab984e0a24ba32cca75f7c54574fa1e2531bb1def21dece8654c1343a56c31ac"
      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  test do
    system "#{bin}/slap", "--help"
  end
end
