# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlapSkills < Formula
  desc "CLI to manage your opencode skills from any git repo"
  homepage "https://github.com/vekzz-dev/slap-skills"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Darwin_x86_64.tar.gz"
      sha256 "244ff9ffad1c7cdff8ecee6e747266755fc07e455bbe76cba3601233212351e6"

      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Darwin_aarch64.tar.gz"
      sha256 "84347354f594a82656d1da49af51a6721cb5e895a464c0fc09b0e84cf2e1731a"

      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Linux_x86_64.tar.gz"
      sha256 "c16436421eb86d0633682e6ad342cbd8c8e274f41877cfa1a73f5ba59080b1da"
      define_method(:install) do
        bin.install "slap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vekzz-dev/slap-skills/releases/download/v0.1.0/slap-skills_Linux_aarch64.tar.gz"
      sha256 "b149adacdbfca7db77911fddc50f9b4a84118b413a0b401bf124e8dd60632060"
      define_method(:install) do
        bin.install "slap"
      end
    end
  end

  test do
    system "#{bin}/slap", "--help"
  end
end
